# -*- coding: utf-8 -*-
"""UniSenac_Correcao_nivelamento_AEDII.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194tgZoyPK7zR7N_-C2kDP6jxe_MRj0e8
"""

# 1) Contar Dígitos Pares

# Ideia:
# Percorrer cada dígito do número e verificar se ele é par (div por 2)

def contar_digitos_pares(numero: int) -> int:
    numero_texto = str(abs(numero))
    quantidade_pares = 0

    for digito in numero_texto:
        if int(digito) % 2 == 0:
            quantidade_pares += 1

    return quantidade_pares



# Exemplo de uso
numero = 248531
resultado = contar_digitos_pares(numero)
print(f"Quantidade de dígitos pares: {resultado}")

# 2) Substituição de Caracteres em String

# Ideia:
# Percorrer a string e trocar toda vogal por *.

def substituir_vogais_por_asterisco(texto: str) -> str:
    # vogais = ["a","e"...]
    vogais = "aeiouAEIOU"
    novo_texto = ""

    for caractere in texto:
        if caractere in vogais:
            novo_texto += "*"
        else:
            novo_texto += caractere

    return novo_texto


# Exemplo de uso
frase = "Algoritmos e Estruturas"
resultado = substituir_vogais_por_asterisco(frase)
print(resultado)

# 3) Reversão com Pilha

# Ideia:
# Usar uma lista como pilha:
# append() para empilhar
# pop() para desempilhar

def inverter_palavra_com_pilha(palavra: str) -> str:
    pilha = []

    for letra in palavra:
        pilha.append(letra)

    palavra_invertida = ""

    while pilha:
        palavra_invertida += pilha.pop()

    return palavra_invertida


# Exemplo de uso
palavra = "python"
resultado = inverter_palavra_com_pilha(palavra)
print(resultado)

# 4) Simulação de Fila

# Ideia:
# Fila funciona no modelo FIFO:
# Primeiro que entra, primeiro que sai.

def mostrar_fila(fila: list) -> None:
    print("Fila atual:", fila)


def enfileirar(fila: list, nome: str) -> None:
    fila.append(nome)
    print(f"{nome} entrou na fila.")
    mostrar_fila(fila)


def desenfileirar(fila: list) -> None:
    if len(fila) == 0:
        print("A fila está vazia.")
        return

    nome_removido = fila.pop(0)
    print(f"{nome_removido} saiu da fila.")
    mostrar_fila(fila)


# Exemplo de uso
fila_nomes = []

enfileirar(fila_nomes, "Pablo")
enfileirar(fila_nomes, "Bruna")
enfileirar(fila_nomes, "Gladimir")

desenfileirar(fila_nomes)
desenfileirar(fila_nomes)

# 5) Remover Elementos Negativos de Lista

# Ideia:
# Criar uma nova lista apenas com os valores maiores ou iguais a zero.

def remover_negativos(lista_numeros: list[int]) -> list[int]:
    nova_lista = []

    for numero in lista_numeros:
        if numero >= 0:
            nova_lista.append(numero)

    return nova_lista


# Exemplo de uso
numeros = [10, -3, 7, -1, 0, 25, -8]
resultado = remover_negativos(numeros)
print(resultado)

# 6) Remover Duplicatas Usando Conjunto

# Ideia:
# O set não permite valores repetidos.

def remover_duplicatas_preservando_ordem(lista_numeros: list[int]) -> list[int]:
    numeros_vistos = set()
    nova_lista = []

    for numero in lista_numeros:
        if numero not in numeros_vistos:
            numeros_vistos.add(numero)
            nova_lista.append(numero)

    return nova_lista


# Exemplo de uso
numeros = [1, 2, 2, 3, 4, 4, 5, 1]
resultado = remover_duplicatas_preservando_ordem(numeros)
print(resultado)

# 7) Contagem de Palavras em String

# Ideia:
# Separar a frase em palavras e contar
# quantas vezes cada uma aparece.


def contar_palavras(frase: str) -> dict[str, int]:
    palavras = frase.lower().split()
    contagem = {}

    for palavra in palavras:
        if palavra in contagem:
            contagem[palavra] += 1
        else:
            contagem[palavra] = 1

    return contagem

# Exemplo de uso
frase = "Bem Legal aprender algoritmos bem cedo"
resultado = contar_palavras(frase)
print(resultado)

# 8) Busca em Dicionário de Contatos

# Ideia:
# Usar um dicionário no formato:
# chave = nome
# valor = telefone

def buscar_telefone(contatos: dict[str, str], nome: str) -> str:
    if nome in contatos:
        return contatos[nome]
    return "Contato não encontrado."


def listar_contatos_ordenados(contatos: dict[str, str]) -> None:

    # Transformar as chaves do dicionário em lista
    nomes = list(contatos.keys())

    # Ordenação manual (Bubble Sort)
    tamanho = len(nomes)

    for i in range(tamanho):
        for j in range(0, tamanho - i - 1):
            if nomes[j] > nomes[j + 1]:
                nomes[j], nomes[j + 1] = nomes[j + 1], nomes[j]

    # Impressão ordenada
    for nome in nomes:
        print(f"{nome}: {contatos[nome]}")


# Exemplo de uso
contatos = {
    "Edecio": "99999-1111",
    "Angelo": "98888-2222",
    "Wagner": "97777-3333"
}

print(buscar_telefone(contatos, "Angelo"))
print(buscar_telefone(contatos, "Pablo"))

print("\nContatos em ordem alfabética:")
listar_contatos_ordenados(contatos)